import "../styles/global.css";
import "../styles/layout.css";
import Providers from "./redux/Providers";
import Menu from "../components/Menu";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex-row justify-center">
            <Menu />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
